# Math and statistics


In [30]:
import numpy as np
from numpy.random import randn

In [31]:
np.set_printoptions(precision=2)

In [32]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [33]:
np.random.seed(25)
b = 36*np.random.randn(6)
b

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [34]:
c = np.arange(1,35)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

### Arithmetic on arrays

In [35]:
a*10

array([10, 20, 30, 40, 50, 60])

In [36]:
b+a

array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  ])

In [37]:
b-a

array([  7.22,  34.97, -33.23, -25.28, -39.45, -14.  ])

In [38]:
b*a

array([   8.22,   73.94,  -90.68,  -85.13, -172.24,  -48.02])

In [39]:
b/a

array([  8.22,  18.48, -10.08,  -5.32,  -6.89,  -1.33])

### Multiplying Matrices and linear algebra

In [40]:
aa = np.array([[2.,4.,6.],[4.,5.,3.],[2.,4.,5.]])
aa

array([[2., 4., 6.],
       [4., 5., 3.],
       [2., 4., 5.]])

In [41]:
bb =  np.array([[0,1.,3.],[0.,2.,1.],[2.,4.,5.]])
bb

array([[0., 1., 3.],
       [0., 2., 1.],
       [2., 4., 5.]])

In [42]:
aa*bb

array([[ 0.,  4., 18.],
       [ 0., 10.,  3.],
       [ 4., 16., 25.]])

In [43]:
np.dot(aa,bb)

array([[12., 34., 40.],
       [ 6., 26., 32.],
       [10., 30., 35.]])